language: python
cache:
  pip: true
  directories:
    - "$HOME/bin"
matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=docs
  - python: "3.6"
    env: TOXENV=flake8
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7-dev"
    env: TOXENV=py37
env:
  global:
    - ESSENTIA_VERSION=2.1_beta2
before_install:
  - export PATH="$HOME/bin:$PATH"
install:
  - travis_retry pip install tox
  - mkdir -p $HOME/bin
  - cd $HOME/bin
  - wget --continue ftp://ftp.acousticbrainz.org/pub/acousticbrainz/essentia-extractor-v$ESSENTIA_VERSION-linux-x86_64.tar.gz
  - tar xfv essentia-extractor-v$ESSENTIA_VERSION-linux-x86_64.tar.gz
  - cd -
script:
  - travis_retry tox
